### ISSUE TITLE
PyCharm project tree view.

### ISSUE THREAD

**Issue by atomekk** [zielu/SVNToolBox#15]
Browsing project tree view under PyCharm 2016.3 requires sometimes two times to open/close it to show directory name instead of only [Svn: branch_name]. 
![selection_014](https://cloud.githubusercontent.com/assets/1046622/21140167/da6a37d0-c136-11e6-9201-542cc3fd7f17.png)

**Comment by zielu** [comment]
Are these 2 separate SVN repositories ?

**Comment by atomekk** [comment]
Under same domain but yes two separate.

**Comment by zielu** [comment]
Attempt to fix in 163.0 as I could not reproduce
