### ISSUE TITLE
Incompatible with IntelliJ 2017.2

### ISSUE THREAD

**Issue by datico** [zielu/SVNToolBox#18]
IntelliJ's Platform and Plugin Updates claims SVNToolBox is incompatible with the newest 2017.2 update.

![screen shot 2017-07-18 at 12 21 52 pm](https://user-images.githubusercontent.com/704221/28335574-b56bd510-6bb3-11e7-82bb-1b2b7a6779de.png)

**Comment by zielu** [comment]
Fixed in 172.0

**Comment by datico** [comment]
You rock. Thanks!!
