### ISSUE TITLE
Status bar always displays "Svn: Not configured"

### ISSUE THREAD

**Issue by strawlink** [zielu/SVNToolBox#24]
![image](https://user-images.githubusercontent.com/6575922/40711318-2e6d3acc-63fb-11e8-9bf3-5cfc11050650.png)

The mousehover tooltip displays the path to the correctly.

I've tried re-installing the plugin without luck.

One thing worth mentioning is that the 'configure branches' popup that is displayed when clicking the status bar differs from the one I get when I open it in the default tool - I have to set up the SVNToolBox manually, and the information is reset now and then (haven't looked into when exactly it happens).

Version Control > Subversion Working Copies Information > Configure Branches (was setup automatically):
![image](https://user-images.githubusercontent.com/6575922/40712154-4aaa6f28-63fd-11e8-9d51-f15022acc94a.png)

Clicking the status bar (setup manually):
![image](https://user-images.githubusercontent.com/6575922/40712215-6c88151e-63fd-11e8-9192-30acc61f5a15.png)

SVNToolBox version: 181.0.0
JetBrains Rider 2018.1.1 (RD-181.4952.276, built on May 24, 2018)

**Comment by zielu** [comment]
Hi, does this happen when you are on prototypes branch or in general ?

**Comment by strawlink** [comment]
In general.

It used to work, but broke a long time ago after a Rider update. I unfortunately don't remember which update it was..

**Comment by strawlink** [comment]
Looks like there was a problem with the solution files - I performed a clean checkout and rebuilt them; the status bar works again :)
