### ISSUE TITLE
Intellij IDEA 2018.3 Crashes with SVNToolBox

### ISSUE THREAD

**Issue by Ceddaerrix** [zielu/SVNToolBox#28]
Intellij IDEA 2018.3 crashes on start when the commands like:
`C:\Users\<current user>\AppData\Roaming\Subversion info --depth empty <Project Directory>\.idea --xml`
`C:\Users\<current user>\AppData\Roaming\Subversion info --depth empty <Project Directory>\<project name>.iml --xml`

returns SVN error:

"svn: E200009: Could not display info for all targets because some targets don't exist"

**Comment by zielu** [comment]
Any error logs from Idea?
